Corrected formatting
eu-cdse/documentation pull request #169
Opened 2023-06-16 14:30 UTC by megha-devaraju

2023-06-19 12:18 UTC, dthiex requested changes
If you didn't know, you can find a deployed version of this here: https://eu-cdse.github.io/documentation/pr-preview/pr-169/Data/Sentinel1.html

Otherwise the changes look okay (besides the small comments I left) but I don't know about the technical correctness of the change (something for Anja/core team to judge).

2023-06-19 12:29 UTC, megha-devaraju commented on Data/Sentinel1.qmd
>  |L0 (RAW) | packed | DAD | World | Oct-14 - Present-1 year | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"
This was the change requested by Anja. These "*" are to be added so it can be used to refer to the notes.

2023-06-19 12:54 UTC, dthiex commented on Data/Sentinel1.qmd
>  |L0 (RAW) | packed | DAD | World | Oct-14 - Present-1 year | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"
@gobaRules I don't think in this table the "*" makes sense (In the upper I understand the explanation but in this table it is not logical for me). How can the product be "temporary offer available until the target service offer becomes available in July 2023" and at the same time be listed in the "July 2023" table?

2023-06-21 06:48 UTC, dthiex commented on Data/Sentinel1.qmd
>  |L0 (RAW) | packed | DAD | World | Oct-14 - Present-1 year | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"
Sure, we can update this, once you have this clarified of next time we update the page.

2023-06-21 06:48 UTC, dthiex approved these changes

2023-06-21 07:58 UTC, merged