Update userguide to include teh new data collections and replace images
eu-cdse/documentation pull request #398
Opened 2023-12-15 15:59 UTC by megha-devaraju

2023-12-18 10:56 UTC, dthiex requested changes

2023-12-18 10:56 UTC, dthiex commented on Applications/_images/Filters.png
I think it's nice that you updated the screenshots with the up-to date ones but we should be careful to not increase the size. I think for the quality of the images it's not necessary and it will just make the whole page slower to load (true for all but especially the big ones).

2023-12-18 10:56 UTC, dthiex commented on Applications/Browser.md
> +With the product search you can find products from Sentinel missions (Sentinel-1, Sentinel-2, Sentinel-3, Sentinel-5p) and the sensors on board these satellites (C-SAR, MSI, OLCI, SRAL, SLSTR, SYNERG
```suggestion
With the product search you can find products from Sentinel missions (Sentinel-1, Sentinel-2, Sentinel-3, Sentinel-5p) and the sensors on board these satellites (C-SAR, MSI, OLCI, SRAL, SLSTR, SYNERGY). You can also find engineering and auxiliary data for all Sentinels (including Sentinel-6). You can explore the metadata for each of those products, download the raw data or visualize the data on the map (at present, Sentinel-1 GRD, Sentinel-2 L1C and L2A, Sentinel-3 OLCI L1B and SLSTR L1B, Sentinel-5P L2 and DEM data can be visualized).
```

2024-01-09 09:29 UTC, dthiex requested changes

2024-01-09 09:29 UTC, dthiex commented on Applications/_images/User_DropDown.png
Please still upload this in a smaller size. The image is later on the page rendered with a width of 250px so no need for such a big file.

2024-01-09 09:29 UTC, dthiex commented
@megha-devaraju Thanks for the updates. I suggest that you check my last comment and once done, assign this back to me for the final review.

May I also suggest that after you changes you leave the comments for me to resolve (once I am happy with the requested changes).

2024-01-23 09:17 UTC, KanerLev commented
@megha-devaraju can you also have a look at the conflict? 

[Conflicting files
Applications/Browser.md]

2024-01-25 07:54 UTC, dthiex approved these changes

2024-01-25 08:39 UTC, merged