openeo restriction when using Sentinel 5P
eu-cdse/documentation pull request #434
Opened 2024-01-29 11:01 UTC by Pratichhya

There is a specific restriction at the moment when accessing or processing Sentinel 5P collection using openEO. 

 Therefore, a callout is at the bottom of the Sentinel 5P data section to aware user to work with single band at once.

2024-01-29 11:30 UTC, jdries commented
Nice! Note that the restriction comes from Sentinelhub, so perhaps it makes sense to mention both API's?

2024-01-29 11:34 UTC, Pratichhya commented
> Nice! Note that the restriction comes from Sentinelhub, so perhaps it makes sense to mention both API's?

Ahh sure, updated :) @majcn please let us know if additional information needs to be integrated from the Sentinel Hub API perspective.

2024-01-29 13:33 UTC, jdries requested changes

2024-01-29 13:33 UTC, jdries commented on Data/SentinelMissions/Sentinel5P.qmd
> +Hence, if you try to load or process two different bands simultaneously using any of these APIs, like methane and NO2, you'll get an error message indicating that the script can only use one product
"!." at end of sentence

2024-01-29 13:33 UTC, jdries commented on Data/SentinelMissions/Sentinel5P.qmd
> +In the present implementation of openEO and Sentinel Hub API, users are limited to processing or downloading only one band at a time when dealing with Sentinel 5P data using openEO.
drop the 'using openEO' at end of sentence, you already mention the API's to which it applies.

2024-01-29 13:41 UTC, Pratichhya commented
Thank you 😅 updated sentences

2024-01-31 22:21 UTC, versniksinergise commented
> > Nice! Note that the restriction comes from Sentinelhub, so perhaps it makes sense to mention both API's?
> 
> Ahh sure, updated :) @versniksinergise please let us know if additional information needs to be integrated from the Sentinel Hub API perspective.

Will do. As of now I am not aware of anything additional

2024-02-01 07:46 UTC, Pratichhya commented
Ahh thank you @versniksinergise and @jdries maybe then, I can merge this PR.

2024-02-01 07:46 UTC, merged