Openeo Rclient
eu-cdse/documentation pull request #553
Opened 2024-06-14 16:42 UTC by Pratichhya

Updated the content.

2024-06-14 18:40 UTC, Pratichhya commented
I believe it is ready to be reviewed, and r works very well with openeo too 😅.

2024-06-18 14:00 UTC, HansVRP commented on APIs/openEO/R_Client/R.qmd
> +Now, let's create fetch and process EO data using openEO. This involves working with "Datacubes," which are fundamental in openEO for representing EO data. For more information on datacubes, refer to
missing coma between create and fetch

2024-06-18 14:10 UTC, HansVRP commented on APIs/openEO/R_Client/R.qmd
> +The objective is to produce a monthly RGB composite of Sentinel 1 backscatter data across Vienna, Austria for three months in 2017. This composite can support tasks like classification and crop monit
I would rather use and instead of or

2024-06-18 14:14 UTC, HansVRP requested changes
Very good, only minor comments. But I will also try to read it on a rendered page

2024-06-18 14:14 UTC, HansVRP commented on APIs/openEO/R_Client/R.qmd
>  # create three monthly sub data sets, which will be merged back into a single data cube later
later on

2024-06-18 14:14 UTC, HansVRP commented on APIs/openEO/R_Client/R.qmd
> +# store the results using the png format and set the create options
do you mean job options?

2024-06-18 14:14 UTC, HansVRP commented on APIs/openEO/R_Client/R.qmd
>  In general the processing workflow works by uploading the Python or R script into the users file directory on the back-end and reference the script via its URL or by its relational name (e.g. `/scrip
very long sentence

2024-06-24 07:14 UTC, Pratichhya commented on APIs/openEO/R_Client/R.qmd
>  # create three monthly sub data sets, which will be merged back into a single data cube later
rephrased

2024-06-28 08:15 UTC, Pratichhya commented
@jdries @HansVRP a kind reminder

2024-06-28 08:47 UTC, jdries commented
@Pratichhya  I won't have time for this, so it's fine to rely on comments by @HansVRP and then merge.

2024-06-28 13:10 UTC, HansVRP commented on APIs/openEO/R_Client/R.qmd
> +The objective is to produce a monthly RGB composite of Sentinel 1 backscatter data across Vienna, Austria for three months in 2017. This composite can support tasks like classification and crop monit
yes indeed I would replace 'and' by 'or'

2024-06-28 13:11 UTC, merged