S3 access guide
eu-cdse/documentation pull request #94
Opened 2023-04-25 08:54 UTC by abuiquoc

guide to access EO data via S3

2023-04-25 13:27 UTC, jdries requested changes
Preview here: https://eu-cdse.github.io/documentation/APIs/S3.html
You will also want to add this new page to the navigation config:
https://github.com/eu-cdse/documentation/blob/publish/_quarto.yml

2023-04-26 11:10 UTC, abuiquoc commented on APIs/S3.md
> +vi .s3cfg
This example assumes use of a Linux environment. Commands does not necessarily have to be executed from a virtual machine, client can access VM that is created on a non-Linux image.

2023-04-26 11:12 UTC, abuiquoc commented on APIs/S3.md
> +Having the access and secret key together with the endpoint, you can use any tool to handle access via S3. Below is an example of how to access EO Data using the s3cmd.
Endpoint will be always the same, we can put "s3.dataspace.copernicus.eu" in this paragraph.

2023-04-26 11:23 UTC, abuiquoc commented on APIs/S3.md
> +# Accces to EO data via S3
_Should we write that this is the preferred and most performant access method?_
It depends on the end user workflow.

 _Are there costs involved for remote access?_
Access to S3 can be requested by any end user for free, however, access (download speed and requests) in the future will be limited, depending on the type of user

2023-04-26 11:31 UTC, jdries commented on APIs/S3.md
> +# Accces to EO data via S3
ok, please add this info. Elaborate a bit on performance and different user workflows?

2023-04-26 11:31 UTC, jdries commented on APIs/S3.md
> +Having the access and secret key together with the endpoint, you can use any tool to handle access via S3. Below is an example of how to access EO Data using the s3cmd.
ok, please add endpoint somewhere at the top

2023-04-26 11:32 UTC, jdries commented on APIs/S3.md
> +vi .s3cfg
ok, please clarify that linux is assumed here, maybe add a link to the tool that you use here

2023-05-10 10:06 UTC, abuiquoc commented
@jdries changes has been added

2023-05-15 13:54 UTC, jdries commented
@abuiquoc  @Pratichhya  the content looks fine, but now the branch has a merge conflict. There's a button to resolve this, can be merged afterwards.

2023-05-17 18:38 UTC, merged

2023-05-17 18:57 UTC, Pratichhya commented
@abuiquoc, Sorry for the delay, it has been merged to the publish branch and will soon reflect on the website.